"""Schemas Pydantic para validação e serialização de dados."""

from app.schemas.auth import (
    AuthStatusResponse,
    LoginRequest,
    LogoutRequest,
    RefreshRequest,
    RegisterRequest,
    TokenResponse,
)
from app.schemas.exercise import (
    AnswerFeedbackResponse,
    ExerciseBase,
    ExerciseCreate,
    ExercisePublicQuestion,
    ExerciseResponse,
    GenerateExercisesRequest,
    PublishExerciseRequest,
    SessionResponse,
    SessionResultResponse,
    StartSessionRequest,
    SubmitAnswerRequest,
)
from app.schemas.user import (
    AccessibilityPreferencesBase,
    AccessibilityPreferencesCreate,
    AccessibilityPreferencesResponse,
    AccessibilityPreferencesUpdate,
    UserBase,
    UserCreate,
    UserResponse,
    UserRole,
    UserUpdate,
)

__all__ = [
    'AccessibilityPreferencesBase',
    'AccessibilityPreferencesCreate',
    'AccessibilityPreferencesResponse',
    'AccessibilityPreferencesUpdate',
    'AnswerFeedbackResponse',
    'AuthStatusResponse',
    'ExerciseBase',
    'ExerciseCreate',
    'ExercisePublicQuestion',
    'ExerciseResponse',
    'GenerateExercisesRequest',
    'LoginRequest',
    'LogoutRequest',
    'PublishExerciseRequest',
    'RefreshRequest',
    'RegisterRequest',
    'SessionResponse',
    'SessionResultResponse',
    'StartSessionRequest',
    'SubmitAnswerRequest',
    'TokenResponse',
    'UserBase',
    'UserCreate',
    'UserResponse',
    'UserRole',
    'UserUpdate',
]
