[project]
name = "app"
version = "0.1.0"
description = "Plataforma Educacional Inclusiva SINA_IA"
authors = [
    {name = "Nicholas", email = "nicholasnas.nn@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard] (>=0.141.1)",
    "pillow (>=12.3.0,<13.0.0)",
    "edge-tts (>=7.2.8,<8.0.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "aiosqlite (>=0.22.1,<0.23.0)",
    "sympy (>=1.14.0,<2.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "python-docx (>=1.2.0,<2.0.0)",
    "pymupdf (>=1.28.2,<2.0.0)",
    "opencv-python-headless (>=5.0.0.93,<6.0.0.0)",
    "google-genai (>=0.1.1)",
    "aiofiles (>=23.2.1)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=8.0.0)",
    "pytest-asyncio (>=0.23.0)",
    "httpx (>=0.27.0)",
    "ruff (>=0.16.5,<0.17.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "poethepoet (>=0.32.0)",
    "typos (>=1.50.0,<2.0.0)"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["app", "."]
addopts = "-p no:warnings --cov=app --cov-context=test"

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']
ignore = ['PLR', 'PLW0717', 'E501']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.typos.files]
extend-exclude = ["*.md"]

[tool.typos.default.extend-words]
denominador = "denominador"
numerador = "numerador"
cliente = "cliente"
Formate = "Formate"
Gere = "Gere"
Erro = "Erro"
Converte = "Converte"
Considere = "Considere"
fundamentais = "fundamentais"
diagramas = "diagramas"
ser = "ser"

[tool.poe] 
poetry_command = ""

[tool.poe.tasks]
lint.sequence = [
  { cmd = "typos" },
  { cmd = "ruff check" },
]
format.sequence = [
  { cmd = "ruff check --fix" },
  { cmd = "ruff format" },
]
serve = "PYTHONPATH=app poetry run uvicorn app.main:app --reload"
test.sequence = [
  "lint",
  { cmd = "pytest -s -x -vv $POE_EXTRA_ARGS" },
  { cmd = "coverage html --show-contexts" },
]
