/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accessibility/files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Generated File */
        get: operations["download_generated_file_api_accessibility_files__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accessibility/process-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Document Stream */
        post: operations["process_document_stream_api_accessibility_process_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audio/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audio File */
        get: operations["get_audio_file_api_audio__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Study Content */
        post: operations["generate_study_content_api_content_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter documento por ID com controle de posse
         * @description Retorna o documento pelo ID. Se pertencer a outro usuário, retorna 404 para privacidade.
         */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercicios/gerar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gerar questões de quiz com auxílio de IA (nascem em rascunho)
         * @description Gera questões com IA. Todas as questões geradas obrigatoriamente nascem com status='rascunho'.
         */
        post: operations["generate_exercises_api_exercicios_gerar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercicios/sessoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sessão de quiz acessível
         * @description Cria uma nova sessão de exercícios com tempo calculado de acordo com as preferências do aluno.
         */
        post: operations["start_session_api_exercicios_sessoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercicios/sessoes/{sessao_id}/proxima": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter próxima questão da sessão (sem gabarito)
         * @description Retorna a próxima questão não respondida da sessão.
         *
         *     GABARITO E EXPLICAÇÃO NUNCA SÃO VAZADOS NESTA ROTA.
         */
        get: operations["get_next_question_api_exercicios_sessoes__sessao_id__proxima_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercicios/sessoes/{sessao_id}/respostas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submeter resposta com validação de tempo no servidor
         * @description Avalia a resposta do aluno e devolve feedback imediato com explicação.
         */
        post: operations["submit_answer_api_exercicios_sessoes__sessao_id__respostas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercicios/sessoes/{sessao_id}/resultado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter placar e resumo pedagógico da sessão
         * @description Retorna o placar formativo da sessão com o detalhamento das respostas.
         */
        get: operations["get_session_result_api_exercicios_sessoes__sessao_id__resultado_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercicios/{exercicio_id}/publicar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publicar questão em rascunho (exclusivo para professor/admin)
         * @description Moderação docente: apenas professores ou administradores podem aprovar e publicar questões.
         */
        post: operations["publish_exercise_api_exercicios__exercicio_id__publicar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Retorna o estado operacional e a versão da API.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materiais": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar os materiais do usuário */
        get: operations["list_materials_api_materiais_get"];
        put?: never;
        /**
         * Enviar um ou mais materiais para processamento
         * @description Valida todos os arquivos antes de gravar qualquer um e responde 202.
         */
        post: operations["upload_materials_api_materiais_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materiais/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status e resultado de um material */
        get: operations["get_material_api_materiais__material_id__get"];
        put?: never;
        post?: never;
        /** Apagar um material e seus arquivos */
        delete: operations["delete_material_api_materiais__material_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materiais/{material_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Áudio MP3 do material, só para quem pode acessá-lo */
        get: operations["get_material_audio_api_materiais__material_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materiais/{material_id}/reprocessar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tentar de novo o processamento de um material com erro */
        post: operations["reprocess_material_api_materiais__material_id__reprocessar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autenticação por e-mail e senha
         * @description Autentica o usuário e emite par de tokens (access e refresh rotativo).
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerramento de sessão e revogação de refresh token
         * @description Revoga o refresh token informado, invalidando a renovação da sessão.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotação de refresh token com detecção de reuso
         * @description Rotaciona o refresh token. Se o token já foi usado, revoga toda a família por segurança.
         */
        post: operations["refresh_token_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registro de novo usuário
         * @description Registra um novo usuário no sistema, criando preferências iniciais e emitindo tokens.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Retorna o estado operacional e a versão da API.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter dados e preferências do usuário logado
         * @description Retorna os dados cadastrais e as preferências UDL do usuário autenticado.
         */
        get: operations["get_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/llm-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Salvar a chave pessoal do Gemini do usuário logado
         * @description Testa a chave no Gemini antes de gravar; string vazia remove a chave.
         */
        put: operations["save_my_llm_key_users_me_llm_key_put"];
        post?: never;
        /**
         * Remover a chave pessoal do Gemini do usuário logado
         * @description Apaga a chave cifrada; as próximas chamadas usam o fallback.
         */
        delete: operations["delete_my_llm_key_users_me_llm_key_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar preferências de acessibilidade do usuário logado
         * @description Atualiza de forma parcial as preferências UDL e de acessibilidade (como VLibras).
         */
        patch: operations["update_my_preferences_users_me_preferences_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessibilityConfig */
        AccessibilityConfig: {
            /**
             * Highlight Key Points
             * @description Destaca ideias centrais e termos-chave para foco visual
             * @default true
             */
            highlight_key_points: boolean;
            /**
             * Include Glossary
             * @description Gera glossário explicativo de termos técnicos complexos
             * @default false
             */
            include_glossary: boolean;
            /**
             * Plain Language
             * @description Se True, simplifica frases e vocabulário (Linguagem Simples)
             * @default false
             */
            plain_language: boolean;
            /**
             * @description Perfil prioritário de acessibilidade
             * @default visual
             */
            profile: components["schemas"]["AccessibilityProfileType"];
            /**
             * Vlibras Active
             * @description Ativação do tradutor de Libras (VLibras) sob demanda
             * @default false
             */
            vlibras_active: boolean;
        };
        /** AccessibilityPreferencesCreate */
        AccessibilityPreferencesCreate: {
            /**
             * Auto Audio
             * @description Reprodução automática do áudio gerado
             * @default false
             */
            auto_audio: boolean;
            /**
             * Dyslexia Font
             * @description Fonte adaptada para dislexia
             * @default false
             */
            dyslexia_font: boolean;
            /**
             * Font Family
             * @description Família tipográfica adaptada (ex: opendyslexic)
             * @default system-ui
             */
            font_family: string;
            /**
             * @description Tamanho da fonte (normal, large, larger)
             * @default normal
             */
            font_size: components["schemas"]["FontSize"];
            /**
             * High Contrast
             * @description Modo de alto contraste para baixa visão
             * @default false
             */
            high_contrast: boolean;
            /**
             * Highlight Key Points
             * @description Destaque visual de ideias centrais
             * @default true
             */
            highlight_key_points: boolean;
            /**
             * Include Glossary
             * @description Glossário automático de termos técnicos
             * @default false
             */
            include_glossary: boolean;
            /**
             * @description Espaçamento entre linhas (normal, relaxed)
             * @default normal
             */
            line_spacing: components["schemas"]["LineSpacing"];
            /**
             * Plain Language
             * @description Simplificação textual e vocabulário acessível
             * @default false
             */
            plain_language: boolean;
            /**
             * @description Perfil prioritário de acessibilidade
             * @default visual
             */
            profile: components["schemas"]["AccessibilityProfileType"];
            /**
             * Vlibras Active
             * @description Ativação do tradutor de Libras (VLibras) sob demanda
             * @default false
             */
            vlibras_active: boolean;
        };
        /** AccessibilityPreferencesResponse */
        AccessibilityPreferencesResponse: {
            /**
             * Auto Audio
             * @description Reprodução automática do áudio gerado
             * @default false
             */
            auto_audio: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Dyslexia Font
             * @description Fonte adaptada para dislexia
             * @default false
             */
            dyslexia_font: boolean;
            /**
             * Font Family
             * @description Família tipográfica adaptada (ex: opendyslexic)
             * @default system-ui
             */
            font_family: string;
            /**
             * @description Tamanho da fonte (normal, large, larger)
             * @default normal
             */
            font_size: components["schemas"]["FontSize"];
            /**
             * High Contrast
             * @description Modo de alto contraste para baixa visão
             * @default false
             */
            high_contrast: boolean;
            /**
             * Highlight Key Points
             * @description Destaque visual de ideias centrais
             * @default true
             */
            highlight_key_points: boolean;
            /** Id */
            id: string;
            /**
             * Include Glossary
             * @description Glossário automático de termos técnicos
             * @default false
             */
            include_glossary: boolean;
            /**
             * @description Espaçamento entre linhas (normal, relaxed)
             * @default normal
             */
            line_spacing: components["schemas"]["LineSpacing"];
            /**
             * Plain Language
             * @description Simplificação textual e vocabulário acessível
             * @default false
             */
            plain_language: boolean;
            /**
             * @description Perfil prioritário de acessibilidade
             * @default visual
             */
            profile: components["schemas"]["AccessibilityProfileType"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** User Id */
            user_id: string;
            /**
             * Vlibras Active
             * @description Ativação do tradutor de Libras (VLibras) sob demanda
             * @default false
             */
            vlibras_active: boolean;
        };
        /** AccessibilityPreferencesUpdate */
        AccessibilityPreferencesUpdate: {
            /** Auto Audio */
            auto_audio?: boolean | null;
            /** Dyslexia Font */
            dyslexia_font?: boolean | null;
            /** Font Family */
            font_family?: string | null;
            font_size?: components["schemas"]["FontSize"] | null;
            /** High Contrast */
            high_contrast?: boolean | null;
            /** Highlight Key Points */
            highlight_key_points?: boolean | null;
            /** Include Glossary */
            include_glossary?: boolean | null;
            line_spacing?: components["schemas"]["LineSpacing"] | null;
            /** Plain Language */
            plain_language?: boolean | null;
            profile?: components["schemas"]["AccessibilityProfileType"] | null;
            /** Vlibras Active */
            vlibras_active?: boolean | null;
        };
        /**
         * AccessibilityProfileType
         * @enum {string}
         */
        AccessibilityProfileType: "visual" | "dyslexia" | "adhd" | "cognitive" | "universal";
        /** AnswerFeedbackResponse */
        AnswerFeedbackResponse: {
            /** Acertou */
            acertou: boolean;
            /** Exercicio Id */
            exercicio_id: string;
            /** Explicacao */
            explicacao: string;
            /** Resposta Aluno */
            resposta_aluno: boolean;
            /** Resposta Correta */
            resposta_correta: boolean;
            /** Tempo Expirado */
            tempo_expirado: boolean;
        };
        /** AuthStatusResponse */
        AuthStatusResponse: {
            /** Message */
            message: string;
        };
        /** Body_process_document_stream_api_accessibility_process_stream_post */
        Body_process_document_stream_api_accessibility_process_stream_post: {
            /** File */
            file: string;
            /**
             * Level
             * @default 2
             */
            level: number;
        };
        /** Body_upload_document_api_documents_upload_post */
        Body_upload_document_api_documents_upload_post: {
            /** File */
            file: string;
        };
        /** Body_upload_materials_api_materiais_post */
        Body_upload_materials_api_materiais_post: {
            /** Ambiente Id */
            ambiente_id?: string | null;
            /** Files */
            files: string[];
            /** Nivel */
            nivel?: number | null;
        };
        /** DocumentProcessResponse */
        DocumentProcessResponse: {
            /** Accessible Text */
            accessible_text: string;
            /** Document Id */
            document_id: string;
            /** Equations Found */
            equations_found: string[];
            /** Extracted Markdown */
            extracted_markdown: string;
            /** Filename */
            filename: string;
        };
        /**
         * ExercisePublicQuestion
         * @description Modelo público da questão para o aluno em teste.
         *
         *     GABARITO E EXPLICAÇÃO SÃO ESTRITAMENTE OMITIDOS AQUI.
         */
        ExercisePublicQuestion: {
            /** Codigo */
            codigo?: string | null;
            /** Enunciado */
            enunciado: string;
            /** Enunciado Falado */
            enunciado_falado: string;
            /** Id */
            id: string;
            /** Linguagem */
            linguagem?: string | null;
            /** Materia Id */
            materia_id: string;
            /** Numero Questao */
            numero_questao: number;
            /** Tempo Limite Segundos */
            tempo_limite_segundos: number;
            /** Tempo Restante Segundos */
            tempo_restante_segundos: number;
            /** Total Questoes */
            total_questoes: number;
        };
        /** ExerciseResponse */
        ExerciseResponse: {
            /**
             * Codigo
             * @description Trecho de código associado à questão
             */
            codigo?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Enunciado
             * @description Texto da questão em Markdown com fórmulas LaTeX
             */
            enunciado: string;
            /** Enunciado Falado */
            enunciado_falado: string;
            /**
             * Explicacao
             * @description Justificativa pedagógica em Linguagem Simples
             */
            explicacao: string;
            /** Fonte */
            fonte: string;
            /** Id */
            id: string;
            /**
             * Linguagem
             * @description Linguagem de programação do trecho de código
             */
            linguagem?: string | null;
            /**
             * Materia Id
             * @description Identificador da matéria / tópico
             */
            materia_id: string;
            /**
             * Resposta Correta
             * @description Gabarito verdadeiro ou falso da assertiva
             */
            resposta_correta: boolean;
            /** Revisado Em */
            revisado_em?: string | null;
            /** Revisado Por */
            revisado_por?: string | null;
            /** Status */
            status: string;
        };
        /**
         * FontSize
         * @enum {string}
         */
        FontSize: "normal" | "large" | "larger";
        /** GenerateExercisesRequest */
        GenerateExercisesRequest: {
            /**
             * Materia Id
             * @description Matéria do exercício
             */
            materia_id: string;
            /**
             * Quantidade
             * @description Quantidade de questões a gerar com a IA
             * @default 3
             */
            quantidade: number;
            /**
             * Texto Base
             * @description Texto base ou transcrição do material para geração
             */
            texto_base: string;
        };
        /** GenerateRequest */
        GenerateRequest: {
            accessibility_config?: components["schemas"]["AccessibilityConfig"] | null;
            /** Document Id */
            document_id: string;
            /**
             * Generate Audio
             * @default true
             */
            generate_audio: boolean;
            /** @default summary */
            generation_type: components["schemas"]["GenerationType"];
            /**
             * @default {
             *       "math_detail_level": "direto",
             *       "pedagogical_level": "basico",
             *       "tone": "formal"
             *     }
             */
            teacher_config: components["schemas"]["TeacherConfig"] | null;
            /**
             * Voice
             * @default pt-BR-AntonioNeural
             */
            voice: string;
        };
        /** GenerationResponse */
        GenerationResponse: {
            /** Accessibility Profile */
            accessibility_profile?: string | null;
            /** Audio Url */
            audio_url?: string | null;
            /**
             * Chave Pessoal Falhou
             * @default false
             */
            chave_pessoal_falhou: boolean;
            /** Document Id */
            document_id: string;
            /** Generation Type */
            generation_type: string;
            /** Spoken Content */
            spoken_content: string;
            /** Text Content */
            text_content: string;
        };
        /**
         * GenerationType
         * @enum {string}
         */
        GenerationType: "summary" | "quiz" | "study_guide";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LLMKeyStatus */
        LLMKeyStatus: {
            /** Llm Key Configurada */
            llm_key_configurada: boolean;
        };
        /** LLMKeyUpdate */
        LLMKeyUpdate: {
            /**
             * Gemini Api Key
             * @description Chave pessoal do Gemini; vazio remove a chave salva
             */
            gemini_api_key: string;
        };
        /**
         * LineSpacing
         * @enum {string}
         */
        LineSpacing: "normal" | "relaxed";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             * @description E-mail cadastrado
             */
            email: string;
            /**
             * Password
             * @description Senha de acesso
             */
            password: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /**
             * Refresh Token
             * @description Token de atualização a revogar
             */
            refresh_token: string;
        };
        /** MaterialDetail */
        MaterialDetail: {
            /** Ambiente Id */
            ambiente_id?: string | null;
            /**
             * Atualizado Em
             * Format: date-time
             */
            atualizado_em: string;
            /** Audio Url */
            audio_url?: string | null;
            /**
             * Chave Pessoal Falhou
             * @default false
             */
            chave_pessoal_falhou: boolean;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            /** Erro Mensagem */
            erro_mensagem?: string | null;
            /** Id */
            id: string;
            /** Mime */
            mime?: string | null;
            /** Nivel */
            nivel?: number | null;
            /** Nome Original */
            nome_original: string;
            /**
             * Reaproveitado
             * @default false
             */
            reaproveitado: boolean;
            /** Resultado */
            resultado?: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @enum {string}
             */
            status: "enviado" | "processando" | "pronto" | "erro";
            /** Tamanho Bytes */
            tamanho_bytes?: number | null;
            /** Texto Acessivel */
            texto_acessivel?: string | null;
            /** Texto Original */
            texto_original?: string | null;
        };
        /** MaterialSummary */
        MaterialSummary: {
            /** Ambiente Id */
            ambiente_id?: string | null;
            /**
             * Chave Pessoal Falhou
             * @default false
             */
            chave_pessoal_falhou: boolean;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            /** Erro Mensagem */
            erro_mensagem?: string | null;
            /** Id */
            id: string;
            /** Mime */
            mime?: string | null;
            /** Nivel */
            nivel?: number | null;
            /** Nome Original */
            nome_original: string;
            /**
             * Reaproveitado
             * @default false
             */
            reaproveitado: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "enviado" | "processando" | "pronto" | "erro";
            /** Tamanho Bytes */
            tamanho_bytes?: number | null;
        };
        /** MaterialUploadResponse */
        MaterialUploadResponse: {
            /** Materiais */
            materiais: components["schemas"]["MaterialSummary"][];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /**
             * Refresh Token
             * @description Token de atualização de sessão
             */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            accessibility_preferences?: components["schemas"]["AccessibilityPreferencesCreate"] | null;
            /**
             * Email
             * Format: email
             * @description E-mail corporativo ou educacional
             */
            email: string;
            /**
             * Full Name
             * @description Nome completo do usuário
             */
            full_name: string;
            /**
             * Password
             * @description Senha com no mínimo 8 caracteres
             */
            password: string;
            /**
             * @description Papel no sistema
             * @default aluno
             */
            role: components["schemas"]["UserRole"];
        };
        /** SessionResponse */
        SessionResponse: {
            /** Finalizado Em */
            finalizado_em?: string | null;
            /** Id */
            id: string;
            /**
             * Iniciado Em
             * Format: date-time
             */
            iniciado_em: string;
            /** Materia Id */
            materia_id?: string | null;
            /** Tempo Limite Segundos */
            tempo_limite_segundos: number;
            /** Total Questoes */
            total_questoes: number;
            /** User Id */
            user_id: string;
        };
        /** SessionResultResponse */
        SessionResultResponse: {
            /** Detalhes */
            detalhes: components["schemas"]["AnswerFeedbackResponse"][];
            /** Percentual Acerto */
            percentual_acerto: number;
            /** Sessao Id */
            sessao_id: string;
            /** Tempo Total Segundos */
            tempo_total_segundos: number;
            /** Total Acertos */
            total_acertos: number;
            /** Total Questoes */
            total_questoes: number;
            /** Total Respondidas */
            total_respondidas: number;
        };
        /** StartSessionRequest */
        StartSessionRequest: {
            /**
             * Materia Id
             * @description Filtrar questões por matéria específica (opcional)
             */
            materia_id?: string | null;
            /**
             * Total Questoes
             * @description Quantidade de questões na sessão de quiz
             * @default 5
             */
            total_questoes: number;
        };
        /** SubmitAnswerRequest */
        SubmitAnswerRequest: {
            /**
             * Exercicio Id
             * @description Identificador da questão
             */
            exercicio_id: string;
            /**
             * Resposta Aluno
             * @description Resposta do aluno: True ou False
             */
            resposta_aluno: boolean;
            /**
             * Tempo Gasto Segundos
             * @description Tempo gasto pelo aluno nesta questão
             * @default 0
             */
            tempo_gasto_segundos: number;
        };
        /** TeacherConfig */
        TeacherConfig: {
            /**
             * Math Detail Level
             * @description direto, passo_a_passo, explicativo
             * @default direto
             */
            math_detail_level: string;
            /**
             * Pedagogical Level
             * @description basico, intermediario, avancado
             * @default basico
             */
            pedagogical_level: string;
            /**
             * Tone
             * @description formal, socrático, encorajador
             * @default formal
             */
            tone: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserResponse */
        UserResponse: {
            accessibility_preferences?: components["schemas"]["AccessibilityPreferencesResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Id */
            id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Llm Key Configurada
             * @description Indica se o usuário tem chave pessoal do Gemini salva
             * @default false
             */
            llm_key_configurada: boolean;
            /** @default aluno */
            role: components["schemas"]["UserRole"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Id */
            version_id: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "aluno" | "professor" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    download_generated_file_api_accessibility_files__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_document_stream_api_accessibility_process_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_process_document_stream_api_accessibility_process_stream_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audio_file_api_audio__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_study_content_api_content_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_exercises_api_exercicios_gerar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateExercisesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_api_exercicios_sessoes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_next_question_api_exercicios_sessoes__sessao_id__proxima_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExercisePublicQuestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_api_exercicios_sessoes__sessao_id__respostas_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessao_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_result_api_exercicios_sessoes__sessao_id__resultado_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_exercise_api_exercicios__exercicio_id__publicar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercicio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_materials_api_materiais_get: {
        parameters: {
            query?: {
                ambiente_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_materials_api_materiais_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_materials_api_materiais_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_materiais__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_material_api_materiais__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_audio_api_materiais__material_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_material_api_materiais__material_id__reprocessar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    save_my_llm_key_users_me_llm_key_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMKeyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMKeyStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_my_llm_key_users_me_llm_key_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_my_preferences_users_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessibilityPreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessibilityPreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
